spring:
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 10
  datasource:
    username: root
    url: jdbc:mysql://mysql:3306/portfolio
    password: ENC(K37xXkw3Y96TMGe+dI/YSEk9/7bAPEC7)
    driver-class-name: com.mysql.cj.jdbc.Driver